version: "3"

services:
  # Our application
  app:
    depends_on:
      - sqelf
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"
  
  sqelf:
    image: datalust/sqelf
    ports:
    - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    depends_on:
      - seq

  seq:
    image: datalust/seq
    ports:
    - "5341:80"
    environment:
    - ACCEPT_EULA=Y
